### ISSUE TITLE
Missed install instruction

### ISSUE THREAD

**Issue by drfenixion** [aerostack2/aerostack2.github.io#29]
### ROS2 Version

humble

### Version

main

### What happened?

Should be added to https://aerostack2.github.io/_02_examples/index.html#basics-examples

installation of iputils-ping
to
`sudo apt install tmux tmuxinator -y`
like `sudo apt install tmux tmuxinator iputils-ping -y`

Because it uses ping command then test connection.
 `ping -c 1 -W 1 google.com > /dev/null 2>&1`
here `aerostack2_ws/src/aerostack2/as2_cli/bash_utils/as2_projects.bash`

If dont do that it will throw message about missed internet connection.

**Comment by pariaspe** [comment]
Done in #30 . Thanks for the report
