### ISSUE TITLE
Unable to locate package

### ISSUE THREAD

**Issue by Omar-Salem** [aerostack2/aerostack2.github.io#50]
When running `sudo apt install ros-humble-aerostack2 ros-humble-as2-gazebo-assets ros-humble-as2-platform-gazebo`
I get the message: `Unable to locate package ros-humble-as2-gazebo-assets`, even after updating/upgrading the repos.

System info:
PRETTY_NAME="Ubuntu 22.04.3 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.3 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

**Comment by pariaspe** [comment]
Solved in v1.0.9 and upcoming releases
