### ISSUE TITLE
Control gimbal using as2_python_api.modules.point_gimbal_module.PointGimbalModule

### ISSUE THREAD

**Issue by OdedHorowits** [aerostack2/aerostack2.github.io#67]
Hello

I use Gazebo with Aerostack2.
I added a gimbal with a camera as can be seen here:
```json
{
    "world_name": "my_world",
    "drones": [
        {
            "model_type": "quadrotor_base",
            "model_name": "drone0",
            "xyz": [0.0, 0.0, 0.3],
            "rpy": [0, 0, 0],
            "flight_time": 60,
            "payload": [
		        {
                    "model_type": "gimbal_position",
                    "model_name": "gb",
                    "payload":
                    {
                        "model_type": "rgbd_camera",
                        "model_name": "rgbd_camera"
                    }
                }
	        ]
        }
    ]
}
```

* I try to use the `PointGimbalModule` module to control the gimbal with no success.
* I think the main problem is that I don't know the correct `frame_id` parameter that need to be supplied to `point_gimbal(self, _x: float, _y: float, _z: float, frame_id: str)` - I tried `earth`, `base_link`, `drone0/base_link` but nothing seems to work.
My code just gets to the point where I call `point_gimbal()` and holds.
I added a debug msg at that function and I can see it is printed (at `/opt/ros/humble/lib/python3.10/site-packages/as2_python_api/modules/point_gimbal_module.py`) 

* I tried to send a direct `geometry_msgs/msg/Vector3Stamped` msg to the topic `/sensor_measurements/gb/twist`, it gets sent every 1 second with no effect.
* Also tried to send a direct `as2_msgs/msg/GimbalControl` msg to `/drone0/platform/gb/gimbal_control` with the same result.

What is the right way to control the gimbal?

Thank you

**Comment by OdedHorowits** [comment]
That definitely did the trick.
I must mention to praise the speed of your response in the forum.
However, I must point out that the documentation is really lacking...

**Comment by pariaspe** [comment]
> That definitely did the trick.
> I must mention to praise the speed of your response in the forum.
> However, I must point out that the documentation is really lacking...

Sure, the documentation has a lot of work to do and we are working on solving this. Notice that Aerostack2 is open source and we are willing to receive pull request with any improvement, including the documentation
