### ISSUE TITLE
Error using hexrotor_base with a gimbal

### ISSUE THREAD

**Issue by OdedHorowits** [aerostack2/aerostack2.github.io#68]
Hi

- Using `quadrotor_base` works fine
- Using `quadrotor_base` with a gimbal works fine
- Using `hexrotor_base` works fine
- Using `hexrotor_base` with a gimbal raise an error

I use the following `world.json` file, all I change is the drone model_type, and the presence of a gimbal:
```json
{
    "world_name": "my_world",
    "drones": [
        {
            "model_type": "hexrotor_base",
            "model_name": "drone0",
            "xyz": [0.0, 0.0, 0.3],
            "rpy": [0, 0, 0],
            "flight_time": 60,
            "payload": [
		        {
                    "model_type": "gimbal_position",
                    "model_name": "gb",
                    "payload":
                    {
                        "model_type": "rgbd_camera",
                        "model_name": "rgbd_camera"
                    }
                }
	        ]
        }
    ]
}
```

For `hexrotor_base` with a gimbal, I get the following error:
![Screenshot from 2024-07-08 14-04-49](https://github.com/aerostack2/aerostack2.github.io/assets/15073370/cfac2c42-d4ea-4139-9918-893db257e31f)

Why would there be any problem if it works with a quadrotor_base?
And how do I start to debug it?

Thank you

**Comment by pariaspe** [comment]
Hi, what you mention is a known issue with aerostack2 v1.0.9. It is already solved at the main branch and new releases would include the fix.

**Comment by pariaspe** [comment]
Yes, it is the only option. We are planning to release aerostack2 in the next days
